[package]
name = "antwerp"
version = "0.1.0"
edition = "2021"
description = "A web framework for Github Pages based on Markdown"
license = "MIT"
readme = "README.md"


[profile.dev]
opt-level = 1

[dependencies]
glob = "0.3.0"
marcus = { git = "https://github.com/Malekaia/Marcus" }
regex = "1.7.0"
